[FIRST, MENU_MAIN, RUS_PRESS, MENU_CONSUL, MENU_CITIZENSHIP, MENU_CADRESS, RUS_COUT, MENU_DOCUMENTS,
 MENU_ROUTE, MENU_DOCPASS, RUS_CLOST, MENU_DOCUMENTSBACK, MENU_PRESIDENCE, MENU_REGISTRATION_ACTS, MENU_REGISTRATION_MARRIAGE,
 MENU_DIVORCE, MENU_RBIRTH, MENU_RDEATH, MENU_RPATERNITY, MENU_RLOSTCIT, ENG_KOR] = range(21)